name: sayr_ui_kit
description: Sayr v3 - Design system (Material 3 + RTL)
version: 3.0.0
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  cached_network_image: ^3.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_lucide: ^1.11.0
  flutter_svg: ^2.0.10
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.3.0

flutter:
  uses-material-design: true
