import 'package:clock/clock.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:sayr_core/src/value_objects/ids.dart';

part 'boarding_record.freezed.dart';

/// Method by which a student was recorded as boarded.
enum BoardingMethod {
  /// Scanned a QR code via the driver app.
  qrScan,

  /// Driver manually added the student.
  manual,

  /// Student self check-in (future feature).
  selfCheckIn,
}

/// A short-lived, one-time-use signed token presented as a QR code.
///
/// Generated by the student app every ~30 seconds; consumed by the driver
/// scanner. Designed to prevent screenshot sharing and replay attacks.
@freezed
abstract class BoardingToken with _$BoardingToken {
  const factory BoardingToken({
    required BoardingTokenId id,
    required SubscriptionId subscriptionId,
    required TripId tripId,
    required UserId studentId,
    required String tokenHash,
    required DateTime issuedAt,
    required DateTime expiresAt,
    DateTime? consumedAt,
  }) = _BoardingToken;

  const BoardingToken._();

  /// Whether the token is still valid (not consumed and not expired).
  bool get isValid => consumedAt == null && clock.now().isBefore(expiresAt);

  /// Seconds until this token expires (clamped at 0).
  int get secondsUntilExpiry {
    final diff = expiresAt.difference(clock.now()).inSeconds;
    return diff < 0 ? 0 : diff;
  }
}

/// Immutable record of a student boarding a trip.
@freezed
abstract class BoardingRecord with _$BoardingRecord {
  const factory BoardingRecord({
    required BoardingId id,
    required TripId tripId,
    required UserId studentId,
    required DateTime boardedAt,
    SubscriptionId? subscriptionId,
    String? studentName,
    @Default(BoardingMethod.qrScan) BoardingMethod boardingMethod,
  }) = _BoardingRecord;

  const BoardingRecord._();
}
