-- Migration: 20260607000001_qr_boarding.sql
-- Description: QR-based boarding system with rotating tokens, geo verification,
--              and atomic validation. Prevents license fraud and supports
--              passenger list per trip.

-- ============================================================================
-- TABLES
-- ============================================================================

-- Boarding tokens: short-lived, one-time-use signed identifiers.
-- Generated by student app every ~30s; consumed by driver scanner.
CREATE TABLE public.boarding_tokens (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  subscription_id UUID NOT NULL REFERENCES public.subscriptions(id) ON DELETE CASCADE,
  trip_id UUID NOT NULL REFERENCES public.trips(id) ON DELETE CASCADE,
  student_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ,
  consumed_by_trip_id UUID REFERENCES public.trips(id) ON DELETE SET NULL
);

CREATE INDEX idx_boarding_tokens_sub ON public.boarding_tokens(subscription_id);
CREATE INDEX idx_boarding_tokens_trip ON public.boarding_tokens(trip_id);
CREATE INDEX idx_boarding_tokens_expires ON public.boarding_tokens(expires_at);
-- Composite index for the cleanup query in generate_boarding_token:
-- "revoke any older unused tokens for this student+trip"
CREATE INDEX idx_boarding_tokens_student_trip_active
  ON public.boarding_tokens(student_id, trip_id)
  WHERE consumed_at IS NULL AND expires_at > NOW();
-- Index for audit/diagnostics queries that filter consumed tokens
CREATE INDEX idx_boarding_tokens_consumed
  ON public.boarding_tokens(consumed_by_trip_id, consumed_at DESC)
  WHERE consumed_at IS NOT NULL;

ALTER TABLE public.boarding_tokens ENABLE ROW LEVEL SECURITY;

-- Only the token owner can see/insert their own tokens.
CREATE POLICY "boarding_tokens_select_own"
  ON public.boarding_tokens FOR SELECT
  TO authenticated
  USING (student_id = auth.uid());

CREATE POLICY "boarding_tokens_insert_own"
  ON public.boarding_tokens FOR INSERT
  TO authenticated
  WITH CHECK (student_id = auth.uid());

-- Drivers can read tokens only via the secure RPC (not via direct table access).
-- We keep RLS strict; the RPC is SECURITY DEFINER.

-- Boarding records: immutable log of who actually boarded which trip.
CREATE TABLE public.boardings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  trip_id UUID NOT NULL REFERENCES public.trips(id) ON DELETE CASCADE,
  subscription_id UUID NOT NULL REFERENCES public.subscriptions(id) ON DELETE RESTRICT,
  student_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  boarded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  boarded_lat NUMERIC(10, 7),
  boarded_lng NUMERIC(10, 7),
  boarding_method TEXT NOT NULL DEFAULT 'qr_scan'
    CHECK (boarding_method IN ('qr_scan', 'manual', 'self_check_in')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- A student can board a given trip at most once.
  CONSTRAINT uq_boardings_trip_student UNIQUE (trip_id, student_id)
);

CREATE INDEX idx_boardings_trip ON public.boardings(trip_id);
CREATE INDEX idx_boardings_student ON public.boardings(student_id);
CREATE INDEX idx_boardings_trip_created ON public.boardings(trip_id, created_at DESC);

ALTER TABLE public.boardings ENABLE ROW LEVEL SECURITY;

-- Students can read their own boarding records.
CREATE POLICY "boardings_select_own_student"
  ON public.boardings FOR SELECT
  TO authenticated
  USING (student_id = auth.uid());

-- Drivers can read boardings for their own trips.
CREATE POLICY "boardings_select_driver_trip"
  ON public.boardings FOR SELECT
  TO authenticated
  USING (
    trip_id IN (
      SELECT t.id FROM public.trips t
      JOIN public.drivers d ON t.driver_id = d.id
      WHERE d.user_id = auth.uid()
    )
  );

-- Admins can read all boardings.
CREATE POLICY "boardings_select_admin"
  ON public.boardings FOR SELECT
  TO authenticated
  USING (public.is_admin());

-- ============================================================================
-- RPC: generate_boarding_token
-- ============================================================================
-- Student calls this every ~30s to fetch a fresh QR token.
-- Returns: { token, expires_at }
--
-- Validation:
--   1. Rate limit (max 6 calls/min — token rotates every 10s, allow overhead)
--   2. Subscription must be active and not expired
--   3. Subscription must be for the trip's route
--   4. Trip must exist and be in driver_waiting/in_transit
--   5. Time window: now must be between (scheduled_at - 30min) and
--      (scheduled_at + 2h)
CREATE OR REPLACE FUNCTION public.generate_boarding_token(
  p_trip_id UUID
)
RETURNS TABLE (
  token TEXT,
  expires_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id UUID := auth.uid();
  v_subscription RECORD;
  v_trip RECORD;
  v_now TIMESTAMPTZ := NOW();
  v_token_raw TEXT;
  v_token_hash TEXT;
  v_expires_at TIMESTAMPTZ;
  v_window_start TIMESTAMPTZ;
  v_window_end TIMESTAMPTZ;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = 'P0001';
  END IF;

  -- Rate limit: 6 calls/minute
  IF NOT public.check_rate_limit(v_user_id, 'generate_boarding_token', 6, 60) THEN
    RAISE EXCEPTION 'Too many token requests, slow down'
      USING ERRCODE = 'P0001';
  END IF;

  -- Look up an active subscription for this student's trips on this route.
  -- The student can have only one active subscription per route (enforced elsewhere),
  -- so we take the most recent active one.
  SELECT s.id, s.student_id, s.route_id, s.status, s.end_date
  INTO v_subscription
  FROM public.subscriptions s
  WHERE s.student_id = v_user_id
    AND s.status = 'active'
    AND (s.end_date IS NULL OR s.end_date > v_now)
  ORDER BY s.start_date DESC
  LIMIT 1;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'No active subscription found'
      USING ERRCODE = 'P0001';
  END IF;

  -- Look up the trip.
  SELECT t.id, t.route_id, t.status, t.scheduled_at, t.started_at
  INTO v_trip
  FROM public.trips t
  WHERE t.id = p_trip_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Trip not found' USING ERRCODE = 'P0001';
  END IF;

  -- Subscription must match trip's route.
  IF v_subscription.route_id != v_trip.route_id THEN
    RAISE EXCEPTION 'Subscription is for a different route'
      USING ERRCODE = 'P0001';
  END IF;

  -- Trip must be in a boardable state.
  IF v_trip.status NOT IN ('driver_waiting', 'in_transit') THEN
    RAISE EXCEPTION 'Trip is not currently accepting boardings'
      USING ERRCODE = 'P0001';
  END IF;

  -- Time window: 30 min before scheduled, 2h after started.
  v_window_start := v_trip.scheduled_at - INTERVAL '30 minutes';
  v_window_end := COALESCE(v_trip.started_at, v_trip.scheduled_at) + INTERVAL '2 hours';

  IF v_now < v_window_start OR v_now > v_window_end THEN
    RAISE EXCEPTION 'Boarding is not allowed at this time'
      USING ERRCODE = 'P0001';
  END IF;

  -- Prevent duplicate boarding.
  IF EXISTS (
    SELECT 1 FROM public.boardings
    WHERE trip_id = p_trip_id AND student_id = v_user_id
  ) THEN
    RAISE EXCEPTION 'You have already boarded this trip'
      USING ERRCODE = 'P0001';
  END IF;

  -- Generate a 32-byte random token (URL-safe base64).
  v_token_raw := encode(gen_random_bytes(32), 'hex');
  v_token_hash := encode(digest(v_token_raw, 'sha256'), 'hex');
  v_expires_at := v_now + INTERVAL '60 seconds';

  -- Best-effort cleanup: revoke any older unused tokens for this student+trip.
  UPDATE public.boarding_tokens
  SET expires_at = v_now
  WHERE student_id = v_user_id
    AND trip_id = p_trip_id
    AND consumed_at IS NULL
    AND expires_at > v_now;

  -- Insert the new token.
  INSERT INTO public.boarding_tokens (
    subscription_id, trip_id, student_id, token_hash, expires_at
  )
  VALUES (
    v_subscription.id, p_trip_id, v_user_id, v_token_hash, v_expires_at
  );

  RETURN QUERY SELECT v_token_raw, v_expires_at;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.generate_boarding_token(UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.generate_boarding_token(UUID) TO authenticated;

-- ============================================================================
-- RPC: validate_boarding
-- ============================================================================
-- Driver calls this after scanning a student's QR code.
-- Returns the boarding record (with student info).
--
-- Validation:
--   1. Caller must be the driver of this trip
--   2. Trip must be in driver_waiting/in_transit
--   3. Token must exist, be unconsumed, and not expired
--   4. Token's trip must match the scanned trip
--   5. Driver's location must be within 500m of trip's last known location
--      (proxy for being at the bus). 500m is a generous radius for pickup.
--   6. Atomic: creates boarding record, marks token consumed
CREATE OR REPLACE FUNCTION public.validate_boarding(
  p_token TEXT,
  p_trip_id UUID,
  p_lat NUMERIC DEFAULT NULL,
  p_lng NUMERIC DEFAULT NULL
)
RETURNS TABLE (
  boarding_id UUID,
  student_id UUID,
  student_name TEXT,
  subscription_id UUID,
  boarded_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id UUID := auth.uid();
  v_trip RECORD;
  v_token_record RECORD;
  v_token_hash TEXT;
  v_boarding_id UUID;
  v_student_name TEXT;
  v_geo_ok BOOLEAN := true;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = 'P0001';
  END IF;

  -- Rate limit: max 30 scans/min per driver.
  IF NOT public.check_rate_limit(v_user_id, 'validate_boarding', 30, 60) THEN
    RAISE EXCEPTION 'Too many scan attempts, slow down'
      USING ERRCODE = 'P0001';
  END IF;

  -- Look up the trip and lock it.
  SELECT t.id, t.driver_id, t.status, t.scheduled_at, t.last_lat, t.last_lng
  INTO v_trip
  FROM public.trips t
  WHERE t.id = p_trip_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Trip not found' USING ERRCODE = 'P0001';
  END IF;

  -- Caller must be the assigned driver.
  IF v_trip.driver_id NOT IN (
    SELECT id FROM public.drivers WHERE user_id = v_user_id
  ) THEN
    RAISE EXCEPTION 'Not authorized for this trip' USING ERRCODE = 'P0001';
  END IF;

  IF v_trip.status NOT IN ('driver_waiting', 'in_transit') THEN
    RAISE EXCEPTION 'Trip is not accepting boardings' USING ERRCODE = 'P0001';
  END IF;

  -- Hash the provided token.
  v_token_hash := encode(digest(p_token, 'sha256'), 'hex');

  -- Look up the token (and lock it).
  SELECT bt.id, bt.subscription_id, bt.trip_id, bt.student_id,
         bt.expires_at, bt.consumed_at
  INTO v_token_record
  FROM public.boarding_tokens bt
  WHERE bt.token_hash = v_token_hash
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Invalid token' USING ERRCODE = 'P0001';
  END IF;

  IF v_token_record.consumed_at IS NOT NULL THEN
    RAISE EXCEPTION 'Token already used' USING ERRCODE = 'P0001';
  END IF;

  IF v_token_record.expires_at < NOW() THEN
    RAISE EXCEPTION 'Token has expired' USING ERRCODE = 'P0001';
  END IF;

  IF v_token_record.trip_id != p_trip_id THEN
    RAISE EXCEPTION 'Token is for a different trip' USING ERRCODE = 'P0001';
  END IF;

  -- Optional geo verification: if driver provided location, ensure they're
  -- within 500m of the trip's last known location.
  IF p_lat IS NOT NULL AND p_lng IS NOT NULL
     AND v_trip.last_lat IS NOT NULL AND v_trip.last_lng IS NOT NULL THEN
    v_geo_ok := (
      -- Haversine simplified: ~111km per degree latitude
      -- 500m ≈ 0.0045 degrees
      ABS(p_lat - v_trip.last_lat) < 0.01
      AND ABS(p_lng - v_trip.last_lng) < 0.01
    );
    IF NOT v_geo_ok THEN
      RAISE EXCEPTION 'Driver location does not match trip location'
        USING ERRCODE = 'P0001';
    END IF;
  END IF;

  -- Look up the student name for the response.
  SELECT full_name INTO v_student_name
  FROM public.profiles
  WHERE id = v_token_record.student_id;

  -- Mark the token as consumed.
  UPDATE public.boarding_tokens
  SET consumed_at = NOW(),
      consumed_by_trip_id = p_trip_id
  WHERE id = v_token_record.id;

  -- Create the boarding record. Unique constraint blocks duplicates.
  BEGIN
    INSERT INTO public.boardings (
      trip_id, subscription_id, student_id, boarded_lat, boarded_lng
    )
    VALUES (
      p_trip_id, v_token_record.subscription_id, v_token_record.student_id,
      p_lat, p_lng
    )
    RETURNING id INTO v_boarding_id;
  EXCEPTION
    WHEN unique_violation THEN
      RAISE EXCEPTION 'Student already boarded this trip'
        USING ERRCODE = 'P0001';
  END;

  -- Audit log.
  INSERT INTO public.audit_logs (user_id, action, entity_type, entity_id, details)
  VALUES (
    v_user_id,
    'student_boarded',
    'trip',
    p_trip_id,
    jsonb_build_object(
      'boarding_id', v_boarding_id,
      'student_id', v_token_record.student_id,
      'lat', p_lat,
      'lng', p_lng
    )
  );

  RETURN QUERY
  SELECT v_boarding_id,
         v_token_record.student_id,
         v_student_name,
         v_token_record.subscription_id,
         NOW();
END;
$$;

REVOKE EXECUTE ON FUNCTION public.validate_boarding(TEXT, UUID, NUMERIC, NUMERIC)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.validate_boarding(TEXT, UUID, NUMERIC, NUMERIC)
  TO authenticated;

-- ============================================================================
-- RPC: get_trip_passengers
-- ============================================================================
-- Returns the list of students who have boarded a given trip.
-- Visible to the assigned driver and to admins.
CREATE OR REPLACE FUNCTION public.get_trip_passengers(
  p_trip_id UUID
)
RETURNS TABLE (
  boarding_id UUID,
  student_id UUID,
  student_name TEXT,
  boarded_at TIMESTAMPTZ,
  boarding_method TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Verify caller is the driver of this trip or an admin.
  IF NOT public.is_admin() AND NOT EXISTS (
    SELECT 1 FROM public.trips t
    JOIN public.drivers d ON t.driver_id = d.id
    WHERE t.id = p_trip_id AND d.user_id = auth.uid()
  ) THEN
    RAISE EXCEPTION 'Not authorized to view passengers'
      USING ERRCODE = 'P0001';
  END IF;

  RETURN QUERY
  SELECT b.id,
         b.student_id,
         p.full_name,
         b.boarded_at,
         b.boarding_method
  FROM public.boardings b
  JOIN public.profiles p ON p.id = b.student_id
  WHERE b.trip_id = p_trip_id
  ORDER BY b.boarded_at ASC;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.get_trip_passengers(UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_trip_passengers(UUID) TO authenticated;

-- ============================================================================
-- RPC: get_active_trip_for_route (helper for student QR page)
-- ============================================================================
-- Returns the current active trip (driver_waiting or in_transit) for a route
-- the student has an active subscription on. Used to auto-detect which trip
-- to generate a QR token for.
CREATE OR REPLACE FUNCTION public.get_active_trip_for_route(
  p_route_id UUID
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_trip_id UUID;
BEGIN
  SELECT t.id INTO v_trip_id
  FROM public.trips t
  WHERE t.route_id = p_route_id
    AND t.status IN ('driver_waiting', 'in_transit')
  ORDER BY t.scheduled_at DESC
  LIMIT 1;

  RETURN v_trip_id;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.get_active_trip_for_route(UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_active_trip_for_route(UUID) TO authenticated;

-- ============================================================================
-- HYBRID BLE PROXIMITY BOARDING EXTENSION
-- ============================================================================

-- Add BLE OTP columns to trips table if they do not exist
ALTER TABLE public.trips 
  ADD COLUMN IF NOT EXISTS ble_otp TEXT,
  ADD COLUMN IF NOT EXISTS ble_otp_expires_at TIMESTAMPTZ;

-- Secure RPC to validate boarding via BLE proximity
CREATE OR REPLACE FUNCTION public.validate_boarding_via_proximity(
  p_trip_id UUID,
  p_otp TEXT,
  p_student_lat NUMERIC DEFAULT NULL,
  p_student_lng NUMERIC DEFAULT NULL
)
RETURNS TABLE (
  boarding_id UUID,
  student_id UUID,
  student_name TEXT,
  subscription_id UUID,
  boarded_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id UUID := auth.uid();
  v_trip RECORD;
  v_subscription RECORD;
  v_boarding_id UUID;
  v_student_name TEXT;
  v_geo_ok BOOLEAN := true;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = 'P0001';
  END IF;

  -- Rate limit: max 10 check-ins per minute per student.
  IF NOT public.check_rate_limit(v_user_id, 'validate_boarding_via_proximity', 10, 60) THEN
    RAISE EXCEPTION 'Too many attempts, slow down'
      USING ERRCODE = 'P0001';
  END IF;

  -- Look up the trip and lock it.
  SELECT t.id, t.driver_id, t.status, t.last_lat, t.last_lng, t.ble_otp, t.ble_otp_expires_at, t.route_id
  INTO v_trip
  FROM public.trips t
  WHERE t.id = p_trip_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Trip not found' USING ERRCODE = 'P0001';
  END IF;

  IF v_trip.status NOT IN ('driver_waiting', 'in_transit') THEN
    RAISE EXCEPTION 'Trip is not accepting boardings' USING ERRCODE = 'P0001';
  END IF;

  -- Verify BLE OTP
  IF v_trip.ble_otp IS NULL OR v_trip.ble_otp != p_otp THEN
    RAISE EXCEPTION 'Invalid proximity OTP' USING ERRCODE = 'P0001';
  END IF;

  IF v_trip.ble_otp_expires_at < NOW() THEN
    RAISE EXCEPTION 'Proximity OTP has expired' USING ERRCODE = 'P0001';
  END IF;

  -- Look up student's active subscription for this route
  SELECT s.id, s.student_id, s.route_id, s.status, s.end_date, s.license_id
  INTO v_subscription
  FROM public.subscriptions s
  WHERE s.student_id = v_user_id
    AND s.route_id = v_trip.route_id
    AND s.status = 'active'
    AND (s.end_date IS NULL OR s.end_date > NOW())
  ORDER BY s.start_date DESC
  LIMIT 1;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'No active subscription found for this route'
      USING ERRCODE = 'P0001';
  END IF;

  -- Optional geo verification: ensure student is within 50m of driver (approx 0.00045 deg)
  -- 50m is a good radius for BLE proximity validation.
  IF p_student_lat IS NOT NULL AND p_student_lng IS NOT NULL
     AND v_trip.last_lat IS NOT NULL AND v_trip.last_lng IS NOT NULL THEN
    v_geo_ok := (
      ABS(p_student_lat - v_trip.last_lat) < 0.001
      AND ABS(p_student_lng - v_trip.last_lng) < 0.001
    );
    IF NOT v_geo_ok THEN
      RAISE EXCEPTION 'Your location is too far from the bus'
        USING ERRCODE = 'P0001';
    END IF;
  END IF;

  -- Look up student name.
  SELECT full_name INTO v_student_name
  FROM public.profiles
  WHERE id = v_user_id;

  -- Create the boarding record. Unique constraint blocks duplicates.
  BEGIN
    INSERT INTO public.boardings (
      trip_id, subscription_id, student_id, boarded_lat, boarded_lng, boarding_method
    )
    VALUES (
      p_trip_id, v_subscription.id, v_user_id, p_student_lat, p_student_lng, 'self_check_in'
    )
    RETURNING id INTO v_boarding_id;
  EXCEPTION
    WHEN unique_violation THEN
      RAISE EXCEPTION 'You have already boarded this trip'
        USING ERRCODE = 'P0001';
  END;

  -- Audit log.
  INSERT INTO public.audit_logs (user_id, action, entity_type, entity_id, details)
  VALUES (
    v_user_id,
    'student_boarded_proximity',
    'trip',
    p_trip_id,
    jsonb_build_object(
      'boarding_id', v_boarding_id,
      'lat', p_student_lat,
      'lng', p_student_lng,
      'method', 'self_check_in'
    )
  );

  RETURN QUERY
  SELECT v_boarding_id,
         v_user_id,
         v_student_name,
         v_subscription.id,
         NOW();
END;
$$;

REVOKE EXECUTE ON FUNCTION public.validate_boarding_via_proximity(UUID, TEXT, NUMERIC, NUMERIC)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.validate_boarding_via_proximity(UUID, TEXT, NUMERIC, NUMERIC)
  TO authenticated;

